version: '3'

services:
  pg:
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=grablist_auth"
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
    ports:
      - "5432:5432"